//! Interactive SSH host selection via fzf.
//!
//! Lists all configured SSH hosts and presents them in fzf for selection.
//! Prints the selected hostname to stdout for shell integration.
//! Shell wrapper functions (generated by `fterm completion`) capture this
//! output and place it on the command line, preserving history.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use tracing::{debug, warn};

use crate::config::home::get_dir;
use crate::config::hosts;
use crate::config::include::resolve_included_files;
use crate::external::CommandRunner;
use crate::util::files::compress_logs;
use crate::util::fzf;
use crate::util::log_dir;

/// Run the interactive SSH host selection command.
///
/// Compresses old log files, retrieves the list of SSH hosts, and launches
/// fzf for interactive selection. Prints `ssh <hostname>` to stdout on
/// selection so that shell wrappers can place it on the command line.
///
/// Must be invoked from inside a tmux session (`$TMUX` must be set). Running
/// outside tmux would bypass the active-log protection in `compress_logs` and
/// risk clobbering logs of concurrent in-tmux sessions.
///
/// # Errors
///
/// Returns an error if not running inside tmux, or if SSH config parsing or
/// fzf invocation fails.
pub fn run(runner: &dyn CommandRunner) -> Result<i32> {
    if std::env::var_os("TMUX").is_none() {
        anyhow::bail!(
            "fssh requires a running tmux session. \
             Start tmux first, then invoke fssh inside a pane."
        );
    }

    let ssh_home = get_dir();
    run_inner(runner, &ssh_home, run_fzf_selection)
}

/// Core logic for SSH host selection, parameterized for testability.
///
/// Accepts an `ssh_home` path and a selection function so callers can
/// substitute the interactive fzf UI with a test double.
#[tracing::instrument(skip(runner, select_fn), err)]
fn run_inner<F>(runner: &dyn CommandRunner, ssh_home: &Path, select_fn: F) -> Result<i32>
where
    F: FnOnce(&[String], &[PathBuf]) -> Result<Option<String>>,
{
    // Compress old log files
    compress_old_logs(runner);

    // Gather SSH hosts
    let config_path = ssh_home.join("config");

    if !config_path.exists() {
        warn!("SSH config not found at {}", config_path.display());
        return Ok(1);
    }

    let config_files = resolve_included_files(&config_path, ssh_home)
        .context("failed to resolve SSH config includes")?;

    let host_list = hosts::get_all(&config_files).context("failed to get SSH host list")?;

    if host_list.is_empty() {
        warn!("no SSH hosts found in config");
        return Ok(1);
    }

    debug!(count = host_list.len(), "found SSH hosts");

    let selected = select_fn(&host_list, &config_files).context("fzf host selection failed")?;

    if let Some(hostname) = selected {
        let trimmed = hostname.trim();
        if trimmed.is_empty() {
            return Ok(1);
        }
        #[allow(clippy::print_stdout)]
        {
            println!("ssh {trimmed}");
        }
        Ok(0)
    } else {
        debug!("fzf selection cancelled");
        Ok(1)
    }
}

/// Launch fzf with SSH host items and return the selected hostname.
// NOTEST(infra): requires interactive fzf terminal session
#[cfg_attr(coverage_nightly, coverage(off))]
fn run_fzf_selection(hosts: &[String], config_files: &[PathBuf]) -> Result<Option<String>> {
    let files_arg: String = config_files
        .iter()
        .map(|p| format!("'{}'", p.display()))
        .collect::<Vec<_>>()
        .join(" ");
    let preview_cmd = format!(
        "rg -i -I -p -N -A 10 -e '^Host\\s+.*\\b{{}}\\b' {files_arg} 2>/dev/null || echo 'No config found'"
    );

    let opts = fzf::Options {
        height: String::from("60%"),
        reverse: true,
        exact: true,
        ansi: false,
        prompt: String::from("SSH Host> "),
        header: None,
        preview: Some(preview_cmd),
        preview_window: Some(String::from("right:50%")),
        border: Some(String::from("rounded")),
        margin: Some(String::from("0,1")),
        delimiter: None,
        nth: None,
        bind: vec![],
    };

    fzf::run(hosts, &opts)
}

/// Compress old `.log` files in the log directory.
fn compress_old_logs(runner: &dyn CommandRunner) {
    let prefix = log_dir::get_prefix();

    let log_dir = std::path::Path::new(&prefix);
    if !log_dir.exists() {
        return;
    }

    match compress_logs(runner, log_dir) {
        Ok(()) => debug!("log compression completed"),
        Err(e) => debug!("log compression failed: {e}"),
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]
    #![allow(clippy::indexing_slicing)]
    #![allow(clippy::undocumented_unsafe_blocks)]
    #![allow(clippy::panic)]

    use std::env;

    use serial_test::serial;
    use tempfile::TempDir;

    use super::*;
    use fterm_core::runner::MockCommandRunner;

    #[cfg_attr(miri, ignore)]
    #[test]
    #[serial(env)]
    fn compress_old_logs_does_not_panic_on_missing_dir() {
        // Arrange
        let runner = MockCommandRunner::new();
        // SAFETY: test runs single-threaded; env var is restored immediately.
        unsafe { env::set_var("FTERM_LOG_DIR_PREFIX", "/nonexistent/path/for/test") };

        // Act — should not panic even if directory does not exist
        compress_old_logs(&runner);

        // Cleanup
        // SAFETY: test runs single-threaded; restoring env state.
        unsafe { env::remove_var("FTERM_LOG_DIR_PREFIX") };
    }

    #[cfg_attr(miri, ignore)]
    #[test]
    #[serial(env)]
    fn compress_old_logs_with_existing_empty_dir() {
        // Arrange — create a real temp dir and point FTERM_LOG_DIR_PREFIX to it
        let dir = tempfile::TempDir::new().unwrap();
        let runner = MockCommandRunner::new();
        // SAFETY: test runs single-threaded; env var is restored immediately.
        unsafe { env::set_var("FTERM_LOG_DIR_PREFIX", dir.path().to_str().unwrap()) };

        // Act — should not panic on an empty but existing directory
        compress_old_logs(&runner);

        // Cleanup
        // SAFETY: test runs single-threaded; restoring env state.
        unsafe { env::remove_var("FTERM_LOG_DIR_PREFIX") };
    }

    #[cfg_attr(miri, ignore)]
    #[test]
    #[serial(env)]
    fn run_inner_no_config_returns_1() {
        // Arrange
        let dir = TempDir::new().unwrap();
        let runner = MockCommandRunner::new();
        unsafe { env::set_var("FTERM_LOG_DIR_PREFIX", "/nonexistent/for/test") };

        // Act
        let result = run_inner(&runner, dir.path(), |_hosts, _files| {
            panic!("select_fn should not be called when config is missing");
        });

        // Assert
        assert_eq!(result.unwrap(), 1);

        // Cleanup
        unsafe { env::remove_var("FTERM_LOG_DIR_PREFIX") };
    }

    #[cfg_attr(miri, ignore)]
    #[test]
    #[serial(env)]
    fn run_inner_empty_host_list_returns_1() {
        // Arrange
        let dir = TempDir::new().unwrap();
        let config = dir.path().join("config");
        std::fs::write(&config, "# Only comments, no Host entries\n").unwrap();
        let runner = MockCommandRunner::new();
        unsafe { env::set_var("FTERM_LOG_DIR_PREFIX", "/nonexistent/for/test") };

        // Act
        let result = run_inner(&runner, dir.path(), |_hosts, _files| {
            panic!("select_fn should not be called when host list is empty");
        });

        // Assert
        assert_eq!(result.unwrap(), 1);

        // Cleanup
        unsafe { env::remove_var("FTERM_LOG_DIR_PREFIX") };
    }

    #[cfg_attr(miri, ignore)]
    #[test]
    #[serial(env)]
    fn run_inner_selection_returns_hostname() {
        // Arrange
        let dir = TempDir::new().unwrap();
        let config = dir.path().join("config");
        std::fs::write(&config, "Host alpha\n  HostName alpha.example.com\n").unwrap();
        let runner = MockCommandRunner::new();
        unsafe { env::set_var("FTERM_LOG_DIR_PREFIX", "/nonexistent/for/test") };

        // Act
        let result = run_inner(&runner, dir.path(), |_hosts, _files| {
            Ok(Some(String::from("alpha")))
        });

        // Assert
        assert_eq!(result.unwrap(), 0);

        // Cleanup
        unsafe { env::remove_var("FTERM_LOG_DIR_PREFIX") };
    }

    #[cfg_attr(miri, ignore)]
    #[test]
    #[serial(env)]
    fn run_inner_selection_cancelled_returns_1() {
        // Arrange
        let dir = TempDir::new().unwrap();
        let config = dir.path().join("config");
        std::fs::write(&config, "Host alpha\n  HostName alpha.example.com\n").unwrap();
        let runner = MockCommandRunner::new();
        unsafe { env::set_var("FTERM_LOG_DIR_PREFIX", "/nonexistent/for/test") };

        // Act
        let result = run_inner(&runner, dir.path(), |_hosts, _files| Ok(None));

        // Assert
        assert_eq!(result.unwrap(), 1);

        // Cleanup
        unsafe { env::remove_var("FTERM_LOG_DIR_PREFIX") };
    }

    #[cfg_attr(miri, ignore)]
    #[test]
    #[serial(env)]
    fn run_inner_selection_empty_string_returns_1() {
        // Arrange
        let dir = TempDir::new().unwrap();
        let config = dir.path().join("config");
        std::fs::write(&config, "Host alpha\n  HostName alpha.example.com\n").unwrap();
        let runner = MockCommandRunner::new();
        unsafe { env::set_var("FTERM_LOG_DIR_PREFIX", "/nonexistent/for/test") };

        // Act
        let result = run_inner(&runner, dir.path(), |_hosts, _files| {
            Ok(Some(String::new()))
        });

        // Assert
        assert_eq!(result.unwrap(), 1);

        // Cleanup
        unsafe { env::remove_var("FTERM_LOG_DIR_PREFIX") };
    }

    #[cfg_attr(miri, ignore)]
    #[test]
    #[serial(env)]
    fn run_inner_select_fn_error_propagates() {
        // Arrange
        let dir = TempDir::new().unwrap();
        let config = dir.path().join("config");
        std::fs::write(&config, "Host beta\n  HostName beta.example.com\n").unwrap();
        let runner = MockCommandRunner::new();
        unsafe { env::set_var("FTERM_LOG_DIR_PREFIX", "/nonexistent/for/test") };

        // Act — select_fn returns an error
        let result = run_inner(&runner, dir.path(), |_hosts, _files| {
            Err(anyhow::anyhow!("fzf crashed unexpectedly"))
        });

        // Cleanup
        unsafe { env::remove_var("FTERM_LOG_DIR_PREFIX") };

        // Assert — error should propagate
        assert!(result.is_err());
        let err_msg = format!("{:#}", result.unwrap_err());
        assert!(
            err_msg.contains("fzf crashed") || err_msg.contains("fzf host selection failed"),
            "unexpected error: {err_msg}"
        );
    }

    #[test]
    #[cfg_attr(miri, ignore)]
    #[serial(env)]
    fn run_bails_when_tmux_not_set() {
        // Arrange — ensure $TMUX is unset.
        unsafe { env::remove_var("TMUX") };
        let runner = MockCommandRunner::new();

        // Act
        let result = run(&runner);

        // Assert
        assert!(result.is_err());
        let err_msg = format!("{:#}", result.unwrap_err());
        assert!(
            err_msg.contains("tmux") || err_msg.contains("TMUX"),
            "unexpected error: {err_msg}"
        );
    }
}
