# - ----------------------------------------------------------------------------
# - Hosts
# - ----------------------------------------------------------------------------
# - options                             parameters
Host org.dev.bastion
    HostName                            bastion.example.com

Host org.dev.bastion-in-node1
    HostName                            192.0.2.1
    ProxyJump                           org.dev.bastion

Host org.dev.localhost
    HostName                            127.0.0.1


# - ----------------------------------------------------------------------------
# - Defaults
# - ----------------------------------------------------------------------------
# - options                             parameters
Host org.dev.*
    User                                cuser
    IdentitiesOnly                      yes
    IdentityFile                        /app/tmp/.ssh/conf.d/keys/private/id_ed25519.pem
    Port                                22
