# - ----------------------------------------------------------------------------
# - Commons
# - ----------------------------------------------------------------------------
# - options                             parameters
Host *
    UpdateHostKeys                      yes
    PreferredAuthentications            publickey,keyboard-interactive,password
    GSSAPIAuthentication                no
    ControlMaster                       auto
    ControlPath                         ~/.ssh/conf.d/cm/mux-%C.sock
    ControlPersist                      30m
    ConnectTimeout                      5
    ConnectionAttempts                  3
    ServerAliveInterval                 50
    ServerAliveCountMax                 5
