# - ----------------------------------------------------------------------------
# - Node
# - ----------------------------------------------------------------------------
# - options                     parameters
Include                         conf.d/nodes/_commons.conf


Include                         conf.d/envs/org/*.conf
